name = "novinky-ze-skolky"
main="index.js"

workers_dev = true

compatibility_date = "2022-09-23"

[[kv_namespaces]]
  binding ="NOVINKY_ZE_SKOLKY"
  id =  "novinky-ze-skolky"
  preview_id = "novinky-ze-skolky-test"